"""init

Revision ID: 0001
Revises:
Create Date: 2026-06-12 10:40:56.388903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dict_biz_domains",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("parent_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "dict_issuers",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("issuer_level", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "documents",
        sa.Column("logical_id", sa.String(length=26), nullable=False),
        sa.Column("corpus_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("logical_id"),
    )
    op.create_table(
        "import_batches",
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("source_dir", sa.String(length=512), nullable=True),
        sa.Column("manifest_path", sa.String(length=512), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_table(
        "doc_versions",
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("logical_id", sa.String(length=26), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("source_format", sa.String(length=8), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_object_key", sa.String(length=512), nullable=False),
        sa.Column("rendition_object_key", sa.String(length=512), nullable=True),
        sa.Column("ir_object_key", sa.String(length=512), nullable=True),
        sa.Column("pipeline_status", sa.String(length=32), nullable=False),
        sa.Column("version_status", sa.String(length=16), nullable=False),
        sa.Column("perm_tag", sa.String(length=32), nullable=True),
        sa.Column("biz_domain", sa.String(length=64), nullable=True),
        sa.Column("issuer", sa.String(length=128), nullable=True),
        sa.Column("doc_number", sa.String(length=128), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("version_relation", sa.String(length=32), nullable=True),
        sa.Column("supersedes_version_id", sa.String(length=26), nullable=True),
        sa.Column("qc_marginal", sa.Boolean(), nullable=False),
        sa.Column("last_error_code", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.batch_id"],
        ),
        sa.ForeignKeyConstraint(
            ["logical_id"],
            ["documents.logical_id"],
        ),
        sa.PrimaryKeyConstraint("doc_version_id"),
    )
    op.create_index(op.f("ix_doc_versions_batch_id"), "doc_versions", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_doc_versions_logical_id"), "doc_versions", ["logical_id"], unique=False
    )
    op.create_index(
        op.f("ix_doc_versions_pipeline_status"), "doc_versions", ["pipeline_status"], unique=False
    )
    op.create_index(
        op.f("ix_doc_versions_source_hash"), "doc_versions", ["source_hash"], unique=False
    )
    op.create_index(
        op.f("ix_doc_versions_supersedes_version_id"),
        "doc_versions",
        ["supersedes_version_id"],
        unique=False,
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.String(length=24), nullable=False),
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("clause_path", sa.String(length=512), nullable=True),
        sa.Column("clause_path_norm", sa.String(length=512), nullable=True),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("breadcrumb", sa.String(length=512), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("is_parent", sa.Boolean(), nullable=False),
        sa.Column("is_table", sa.Boolean(), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("chunk_status", sa.String(length=16), nullable=False),
        sa.Column("dense_vec_cold", postgresql.BYTEA(), nullable=True),
        sa.Column("sparse_vec_cold", postgresql.BYTEA(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_version_id"],
            ["doc_versions.doc_version_id"],
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(op.f("ix_chunks_doc_version_id"), "chunks", ["doc_version_id"], unique=False)
    op.create_table(
        "pipeline_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=16), nullable=True),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_version_id"],
            ["doc_versions.doc_version_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_events_doc_version_id"),
        "pipeline_events",
        ["doc_version_id"],
        unique=False,
    )
    op.create_table(
        "review_queue",
        sa.Column("queue_id", sa.String(length=26), nullable=False),
        sa.Column("queue_type", sa.String(length=16), nullable=False),
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("disposition", sa.String(length=16), nullable=True),
        sa.Column("operator", sa.String(length=64), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_version_id"],
            ["doc_versions.doc_version_id"],
        ),
        sa.PrimaryKeyConstraint("queue_id"),
    )
    op.create_index(
        op.f("ix_review_queue_doc_version_id"), "review_queue", ["doc_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_queue_queue_type"), "review_queue", ["queue_type"], unique=False
    )
    op.create_index(op.f("ix_review_queue_status"), "review_queue", ["status"], unique=False)
    op.create_table(
        "revision_notes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_version_id"],
            ["doc_versions.doc_version_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revision_notes_doc_version_id"), "revision_notes", ["doc_version_id"], unique=False
    )
    op.create_table(
        "clause_tags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chunk_id", sa.String(length=24), nullable=False),
        sa.Column("tag_type", sa.String(length=32), nullable=False),
        sa.Column("tag_value", sa.String(length=64), nullable=False),
        sa.Column("evidence", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.chunk_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clause_tags_chunk_id"), "clause_tags", ["chunk_id"], unique=False)
    op.create_table(
        "remediation_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("doc_version_id", sa.String(length=26), nullable=False),
        sa.Column("queue_id", sa.String(length=26), nullable=True),
        sa.Column("disposition", sa.String(length=16), nullable=False),
        sa.Column("operator", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before_state", sa.String(length=32), nullable=True),
        sa.Column("after_state", sa.String(length=32), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_version_id"],
            ["doc_versions.doc_version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["review_queue.queue_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_remediation_records_doc_version_id"),
        "remediation_records",
        ["doc_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_remediation_records_doc_version_id"), table_name="remediation_records")
    op.drop_table("remediation_records")
    op.drop_index(op.f("ix_clause_tags_chunk_id"), table_name="clause_tags")
    op.drop_table("clause_tags")
    op.drop_index(op.f("ix_revision_notes_doc_version_id"), table_name="revision_notes")
    op.drop_table("revision_notes")
    op.drop_index(op.f("ix_review_queue_status"), table_name="review_queue")
    op.drop_index(op.f("ix_review_queue_queue_type"), table_name="review_queue")
    op.drop_index(op.f("ix_review_queue_doc_version_id"), table_name="review_queue")
    op.drop_table("review_queue")
    op.drop_index(op.f("ix_pipeline_events_doc_version_id"), table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_index(op.f("ix_chunks_doc_version_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_doc_versions_supersedes_version_id"), table_name="doc_versions")
    op.drop_index(op.f("ix_doc_versions_source_hash"), table_name="doc_versions")
    op.drop_index(op.f("ix_doc_versions_pipeline_status"), table_name="doc_versions")
    op.drop_index(op.f("ix_doc_versions_logical_id"), table_name="doc_versions")
    op.drop_index(op.f("ix_doc_versions_batch_id"), table_name="doc_versions")
    op.drop_table("doc_versions")
    op.drop_table("import_batches")
    op.drop_table("documents")
    op.drop_table("dict_issuers")
    op.drop_table("dict_biz_domains")
    # ### end Alembic commands ###
