"""preseg columns

Revision ID: 0013_preseg_columns
Revises: 0012_query_sessions
Create Date: 2026-07-06 11:26:15.374946

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013_preseg_columns"
down_revision: str | None = "0012_query_sessions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cases", sa.Column("persons", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("cases", sa.Column("occurred_at", sa.Date(), nullable=True))
    op.add_column("cases", sa.Column("source_url", sa.String(length=512), nullable=True))
    op.add_column("doc_versions", sa.Column("source_doc_id", sa.String(length=64), nullable=True))
    op.add_column("doc_versions", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "doc_versions", sa.Column("version_status_source", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "doc_versions", sa.Column("issuer_level_src", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "doc_versions", sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("doc_versions", sa.Column("file_no", sa.String(length=128), nullable=True))
    op.add_column(
        "doc_versions", sa.Column("source_created_by", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_doc_versions_source_doc_id"), "doc_versions", ["source_doc_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_doc_versions_source_doc_id"), table_name="doc_versions")
    op.drop_column("doc_versions", "source_created_by")
    op.drop_column("doc_versions", "file_no")
    op.drop_column("doc_versions", "tags")
    op.drop_column("doc_versions", "issuer_level_src")
    op.drop_column("doc_versions", "version_status_source")
    op.drop_column("doc_versions", "content_hash")
    op.drop_column("doc_versions", "source_doc_id")
    op.drop_column("cases", "source_url")
    op.drop_column("cases", "occurred_at")
    op.drop_column("cases", "persons")
    # ### end Alembic commands ###
