"""0003 doc_versions.degraded

Revision ID: 372ac2928246
Revises: 0002
Create Date: 2026-06-15 01:06:38.517535

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "372ac2928246"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "doc_versions", sa.Column("degraded", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doc_versions", "degraded")
    # ### end Alembic commands ###
