"""0004 chunks.oversize

Revision ID: e100748d4864
Revises: 372ac2928246
Create Date: 2026-06-15 01:49:59.413429

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e100748d4864"
down_revision: str | None = "372ac2928246"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("oversize", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "oversize")
    # ### end Alembic commands ###
